
const ActivityTypes = Object.freeze({
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  ADD_EMAIL: 'ADD_EMAIL',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  VERIFY_PHONE: 'VERIFY_PHONE',

  CREATE_STORE: 'CREATE_STORE',
  STORE_APPROVED: 'STORE_APPROVED',
  STORE_LIKED: 'STORE_LIKED',

  NEW_MESSAGE: 'NEW_MESSAGE',
  NEW_COMMENT: 'NEW_COMMENT',
  NEW_LIKE: 'NEW_LIKE',
  NEW_FOLLOW: 'NEW_FOLLOW',
  NEW_UNFOLLOW: 'NEW_UNFOLLOW',
  NEW_SUBSCRIBER: 'NEW_SUBSCRIBER',
  NEW_SUBSCRIPTION: 'NEW_SUBSCRIPTION',
  NEW_LISTING: 'NEW_LISTING',
  LISTING_DELETED: 'LISTING_DELETED',
  NEW_REVIEW: 'NEW_REVIEW',
  NEW_REVIEW_REPLY: 'NEW_REVIEW_REPLY',
  NEW_REVIEW_LIKE: 'NEW_REVIEW_LIKE',
  NEW_REVIEW_UNLIKE: 'NEW_REVIEW_UNLIKE',
  NEW_REVIEW_REPORT: 'NEW_REVIEW_REPORT',
  NEW_REVIEW_REPLY_REPORT: 'NEW_REVIEW_REPLY_REPORT',
  NEW_REVIEW_REPORT_RESOLVED: 'NEW_REVIEW_REPORT_RESOLVED',
});

module.exports = ActivityTypes;