const NotificationTypes = Object.freeze({
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  EMAIL_UNVERIFIED: 'EMAIL_UNVERIFIED',
  STORE_PENDING: 'STORE_PENDING',
  STORE_APPROVED: 'STORE_APPROVED',
  STORE_REJECTED: 'STORE_REJECTED',
  STORE_CREATED: 'STORE_CREATED',
  STORE_FOLLOWED: 'STORE_FOLLOWED',
  STORE_UNFOLLOWED: 'STORE_UNFOLLOWED',
  NEW_STORE: 'NEW_STORE',
  NEW_SUBSCRIBER: 'NEW_SUBSCRIBER',
  NEW_LISTING: 'NEW_LISTING',
  LISTING_DELETED: 'LISTING_DELETED',
  PLAN_SUBSCRIBED: 'PLAN_SUBSCRIBED',
  PAYMENT_SUCCESSFUL: 'PAYMENT_SUCCESSFUL',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  IDENTITY_VERIFICATION: 'IDENTITY_VERIFICATION'
});

module.exports = NotificationTypes;